---
title: "Test script"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
```

Read in data with compounds in rows and samples as columns

```{r}
dummy1<-readxl::read_excel("dummy1.xlsx", na="0")
dummy1<-dummy1 %>% mutate_all(~replace(.,is.na(.), 0))
```


Try to generate column sums, and save them back to the object in a new row:
```{r}
Totals<-dummy1 %>% 
  bind_rows(summarise_all(., list(~if(is.numeric(.)) sum(.) else "Total"))) %>% 
  pivot_longer(cols=starts_with("r"),names_to="Sample_ID") %>% 
  pivot_wider(names_from=Compound, values_from = value)


```

Now loading in the ID information:
```{r}

#this has the information we need for doing the calculations
dummy2<-readxl::read_excel("dummy2.xlsx")

#These functions specify how to calculate what we want: total scent in the sample, and emission rates per flower, per fresh mass, and per dry mass:
T_S<-function(Column, Tol.Area, Tol.Amt, Samp.Vol) {
  Column/Tol.Area*Tol.Amt*Samp.Vol
} 

ER_Fl<-function(Total.Samp, Hrs, Flwrs) {
  Total.Samp/Hrs/Flwrs
}

ER_Fm<-function(Total.Samp, Hrs, Fr.Mass) {
  Total.Samp/Hrs/Fr.Mass
}

ER_Dm<-function(Total.Samp, Hrs, Dr.Mass) {
  Total.Samp/Hrs/Dr.Mass
}

# This code joins the data with the relevant meta data
dummy_wide<-Totals %>%  full_join(dummy2) %>% 
  mutate(Total_Sample=T_S(Total, `toluene area`,`toluene amt`, `sample vol`), ER_flower=ER_Fl(Total_Sample,`no hours`, `no flowers`), ER_fresh=ER_Fm(Total_Sample, `no hours`, `fresh mass`), ER_dry=ER_Dm(Total_Sample, `no hours`, `dry mass`))





dummy_wide<-Totals %>%  full_join(dummy2) %>% 
  mutate_at(c(2:39), Total_Sample=(Total/`toluene area`*`toluene amt`*`sample vol`), ER_flower=Total_Sample/`no hours`/`no flowers`, ER_fresh=Total_Sample/`no hours`/`fresh mass`, ER_dry=Total_Sample/`no hours`/`dry mass`)

## figure out how to apply this mutation to all of the relevant columns

```



